import type { ThemeDefinition } from '../types'

export const darkTheme: ThemeDefinition = {
  name: 'DSH Dark',
  type: 'dark',
  colors: {
    'editor.background': '#1e1e1e',
    'editor.foreground': '#d4d4d4',
    'editor.lineHighlightBackground': '#2a2d2e',
    'editor.selectionBackground': '#264f78',
    'sidebar.background': '#252526',
    'sidebar.foreground': '#cccccc',
    'sidebar.activeBackground': '#37373d',
    'sidebar.activeForeground': '#ffffff',
    'sidebar.border': '#3c3c3c',
    'tab.activeBackground': '#1e1e1e',
    'tab.activeForeground': '#ffffff',
    'tab.inactiveBackground': '#2d2d2d',
    'tab.inactiveForeground': '#969696',
    'tab.activeBorder': '#007acc',
    'tab.border': '#252526',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'statusBar.debuggingBackground': '#bb6517',
    'panel.background': '#1e1e1e',
    'panel.border': '#3c3c3c',
    'panel.activeBackground': '#1e1e1e',
    'panel.activeForeground': '#ffffff',
    'panel.inactiveForeground': '#888888',
    'terminal.background': '#1e1e1e',
    'terminal.foreground': '#cccccc',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiRed': '#f44747',
    'terminal.ansiGreen': '#6a9955',
    'terminal.ansiYellow': '#dcdcaa',
    'terminal.ansiBlue': '#569cd6',
    'terminal.ansiMagenta': '#c586c0',
    'terminal.ansiCyan': '#4ec9b0',
    'terminal.ansiWhite': '#d4d4d4',
    'titleBar.background': '#3c3c3c',
    'titleBar.foreground': '#cccccc',
    'breadcrumb.foreground': '#a9a9a9',
    'breadcrumb.focusForeground': '#ffffff',
    'commandPalette.background': '#252526',
    'commandPalette.foreground': '#cccccc',
    'commandPalette.selectedBackground': '#094771',
    'scrollbarSlider.background': 'rgba(121, 121, 121, 0.4)',
    'scrollbarSlider.hoverBackground': 'rgba(100, 100, 100, 0.7)',
    'scrollbarSlider.activeBackground': 'rgba(191, 191, 191, 0.4)',
    'border': '#3c3c3c',
    'focusBorder': '#007fd4',
    'input.background': '#3c3c3c',
    'input.border': '#3c3c3c',
    'input.foreground': '#cccccc',
    'list.activeSelectionBackground': '#094771',
    'list.activeSelectionForeground': '#ffffff',
    'list.hoverBackground': '#2a2d2e',
    'list.hoverForeground': '#ffffff',
    'badge.background': '#4d4d4d',
    'badge.foreground': '#ffffff',
  },
}

export const getThemeColors = (): ThemeDefinition['colors'] => darkTheme.colors
